### ISSUE TITLE
Upgrade dbt integration to support 1.8

### ISSUE THREAD

**Issue by ernestoongaro** [MetaphorData/connectors#824]
Hi folks!

A customer of dbt Cloud & Metaphor has tried our new "keep on latest version" feature; which sounds like a nightmare for ya'll, but actually we are going to do a much better job in the future of not creating breaking changes between point releases

https://docs.getdbt.com/docs/dbt-versions/upgrade-dbt-version-in-cloud#keep-on-latest-version

It does mean that you'll need to look into supporting our new manifest:
https://schemas.getdbt.com/dbt/manifest/v12

**Comment by alyiwang** [comment]
Thanks @ernestoongaro for this info, really appreciate the backward compatibility. 
We will add the support of the v12 schema soon

**Comment by ernestoongaro** [comment]
Amazing, thanks! You can read more about v1.8 and beyond here https://github.com/dbt-labs/dbt-core/blob/main/docs/roadmap/2023-11-dbt-tng.md#adapters--artifacts
